In [1]:
import numpy as np


In [2]:
# 1. Створіть одновимірний масив (вектор) з першими 20-ма натуральними числами та виведіть його значення.
vector = np.arange(1, 21)
print(vector)


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [3]:
# 2. Створіть двовимірний масив (матрицю) розміром 4x4, заповніть його одиницями та виведіть його значення.
matrix_4x4 = np.ones((4, 4), dtype=int)
print(matrix_4x4)


[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [4]:
# 3. Створіть масив розміром 5x5, заповніть його випадковими дійсними числами в діапазоні від -1 до 1 та виведіть його значення.
arr_5x5 = np.random.uniform(-1, 1, size=(5, 5))
print(arr_5x5)


[[ 0.66104746  0.33556038  0.50884533  0.97436289  0.5516395 ]
 [ 0.53927614 -0.2383505  -0.21056086  0.36338156 -0.43386463]
 [-0.95253398  0.95942967  0.22949179 -0.18893821  0.88396536]
 [ 0.55862665 -0.35418348  0.46148227  0.97869508 -0.20730054]
 [-0.2518661  -0.9948918   0.90910872  0.89897328 -0.11596901]]


In [5]:
# 4. Створіть масив розміром 3x3, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.
arr_3x3 = np.random.random((3, 3))
print(arr_3x3)


[[0.17717314 0.38120862 0.27958399]
 [0.48192173 0.95632554 0.48179022]
 [0.55059339 0.43736287 0.43563376]]


In [6]:
# 5. Створіть два одновимірних масиви розміром 6, заповніть їх випадковими цілими числами в діапазоні від 1 до 20 та виконайте на них поелементні операції додавання, віднімання та множення.
a = np.random.randint(1, 21, size=6)
b = np.random.randint(1, 21, size=6)

print("a =", a)
print("b =", b)
print("a + b =", a + b)
print("a - b =", a - b)
print("a * b =", a * b)


a = [10  5 16  4  6 20]
b = [11  3 19 12  5 10]
a + b = [21  8 35 16 11 30]
a - b = [-1  2 -3 -8  1 10]
a * b = [110  15 304  48  30 200]


In [7]:
# 6. Створіть дві матриці розміром 3x2 та 2x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 5 та перемножте їх між собою.
m1 = np.random.randint(1, 6, size=(3, 2))
m2 = np.random.randint(1, 6, size=(2, 4))

product = m1 @ m2  # матричне множення

print("m1:\n", m1)
print("m2:\n", m2)
print("m1 @ m2:\n", product)


m1:
 [[2 2]
 [3 3]
 [2 3]]
m2:
 [[1 3 1 5]
 [3 3 3 3]]
m1 @ m2:
 [[ 8 12  8 16]
 [12 18 12 24]
 [11 15 11 19]]


In [8]:
# 7. Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.
m = np.random.random((3, 3))
m_T = m.T

print("m:\n", m)
print("m.T:\n", m_T)


m:
 [[0.34180855 0.6533083  0.15406203]
 [0.61561373 0.91393639 0.11139288]
 [0.10474076 0.99499982 0.61804785]]
m.T:
 [[0.34180855 0.61561373 0.10474076]
 [0.6533083  0.91393639 0.99499982]
 [0.15406203 0.11139288 0.61804785]]


In [9]:
# 8. Створіть дві матриці розміром 3x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.
x = np.random.randint(1, 11, size=(3, 3))
y = np.random.randint(1, 11, size=(3, 3))

diff = x - y

print("x:\n", x)
print("y:\n", y)
print("x - y:\n", diff)


x:
 [[ 6  9  4]
 [ 1  1 10]
 [ 7  6  5]]
y:
 [[ 2  9 10]
 [ 9  5  7]
 [ 3 10  3]]
x - y:
 [[ 4  0 -6]
 [-8 -4  3]
 [ 4 -4  2]]


In [10]:
# 9. Створіть дві матриці розміром 3x3, заповніть їх випадковими цілими числами в діапазоні від -5 до 5 та знайдіть їх добуток.
p = np.random.randint(-5, 6, size=(3, 3))
q = np.random.randint(-5, 6, size=(3, 3))

elem_product = p * q  # поелементний добуток

print("p:\n", p)
print("q:\n", q)
print("p * q:\n", elem_product)


p:
 [[-3 -3  4]
 [-5  1  4]
 [-5 -4 -5]]
q:
 [[ 5 -2  4]
 [-1  2  3]
 [-4  2 -1]]
p * q:
 [[-15   6  16]
 [  5   2  12]
 [ 20  -8   5]]


In [11]:
# 10. Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від -1 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.
z = np.random.uniform(-1, 1, size=(3, 3))
row_sums_col = z.sum(axis=1).reshape(-1, 1)  # робимо саме стовпчик

print("z:\n", z)
print("Суми рядків (стовпчик):\n", row_sums_col)


z:
 [[-0.76560845 -0.71022548 -0.37976013]
 [ 0.49618435  0.60388706  0.6003789 ]
 [-0.15819025 -0.08894865  0.65125166]]
Суми рядків (стовпчик):
 [[-1.85559406]
 [ 1.70045031]
 [ 0.40411276]]


Посилання на GitHub: